export {default as Container} from "./container"
export {default as Game} from "./game"
export {default as UpdatePassword} from "./updatePassword"
export {default as LanguageAndTheme} from "./languageAndtheme"
export {default as MainComponent} from "./mainComponent"